using System.ComponentModel;
using System.Reflection;
using System.Text.Json;
using Google.Protobuf;
using Microsoft.Extensions.Logging;
using DataAnnotations = System.ComponentModel.DataAnnotations;

namespace Aevatar.Agents.AI.WithTool.Abstractions;

/// <summary>
/// Strongly-typed tool base class
/// Automatically handles parameter conversion, validation, and execution
/// </summary>
/// <typeparam name="TInput">Input parameter type</typeparam>
/// <typeparam name="TOutput">Output result type</typeparam>
public abstract class TypedAevatarToolBase<TInput, TOutput> : AevatarToolBase
    where TInput : class
    where TOutput : IMessage
{
    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        PropertyNameCaseInsensitive = true,
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase
    };

    /// <summary>
    /// Strongly-typed execution method (must be implemented by subclasses)
    /// </summary>
    /// <param name="input">Validated strongly-typed input parameters</param>
    /// <param name="context">Tool context</param>
    /// <param name="logger">Logger</param>
    /// <param name="cancellationToken">Cancellation token</param>
    /// <returns>Strongly-typed execution result</returns>
    protected abstract Task<TOutput> ExecuteTypedAsync(
        TInput input,
        ToolContext context,
        ILogger? logger,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Implements AevatarToolBase's ExecuteAsync
    /// Automatically handles Dictionary to strongly-typed conversion and validation
    /// </summary>
    public sealed override async Task<IMessage> ExecuteAsync(
        Dictionary<string, object> parameters,
        ToolContext context,
        ILogger? logger,
        CancellationToken cancellationToken = default)
    {
        // DEBUG: Log raw parameters
        logger?.LogWarning("[DEBUG] Tool {Name} raw parameters count: {Count}", Name, parameters.Count);
        foreach (var kvp in parameters)
        {
            logger?.LogWarning("[DEBUG] Param {Key}: {Value} (Type: {Type})", 
                kvp.Key, kvp.Value, kvp.Value?.GetType().Name ?? "null");
        }

        // 1. Serialize Dictionary to JSON
        var json = JsonSerializer.Serialize(parameters, JsonOptions);
        logger?.LogWarning("[DEBUG] Serialized JSON: {Json}", json);

        try 
        {
            // 2. Deserialize to strongly-typed object
            var input = JsonSerializer.Deserialize<TInput>(json, JsonOptions);
            
            if (input == null)
            {
                logger?.LogError("[DEBUG] Deserialization returned null for {Json}", json);
                throw new ArgumentException(
                    $"Failed to deserialize parameters for tool '{Name}'. " +
                    $"Expected type: {typeof(TInput).Name}, Received: {json}");
            }

            logger?.LogWarning("[DEBUG] Deserialized input: {Input}", input);

            // 3. Validate input parameters (using DataAnnotations)
            ValidateInput(input);
            logger?.LogWarning("[DEBUG] Validation passed");

            // 4. Execute strongly-typed method
            var result = await ExecuteTypedAsync(input, context, logger, cancellationToken);
            logger?.LogWarning("[DEBUG] Execution result: {Result}", result);
            return result;
        }
        catch (Exception ex)
        {
            logger?.LogError(ex, "[DEBUG] Error in ExecuteAsync for {Name}", Name);
            throw;
        }
    }

    /// <summary>
    /// Automatically generate ToolParameters
    /// Generated by reflecting TInput's properties and DataAnnotations
    /// </summary>
    public sealed override ToolParameters CreateParameters()
    {
        return TypedToolParameterGenerator.Generate<TInput>();
    }

    /// <summary>
    /// Validate input object using DataAnnotations
    /// </summary>
    /// <param name="input">Input object to validate</param>
    /// <exception cref="DataAnnotations.ValidationException">Thrown when validation fails</exception>
    private static void ValidateInput(TInput input)
    {
        var validationContext = new DataAnnotations.ValidationContext(input);
        var validationResults = new List<DataAnnotations.ValidationResult>();
        
        var isValid = DataAnnotations.Validator.TryValidateObject(
            input, 
            validationContext, 
            validationResults, 
            validateAllProperties: true);
        
        if (!isValid)
        {
            var errors = validationResults
                .Select(r => r.ErrorMessage)
                .Where(msg => !string.IsNullOrEmpty(msg))
                .ToList();
            
            var errorMessage = string.Join("; ", errors);
            throw new DataAnnotations.ValidationException(
                $"Parameter validation failed for tool '{typeof(TInput).Name}': {errorMessage}");
        }
    }
}

/// <summary>
/// Automatic parameter generator
/// Automatically generates ToolParameters from strongly-typed class DataAnnotations
/// </summary>
public static class TypedToolParameterGenerator
{
    /// <summary>
    /// Generate ToolParameters from generic type
    /// </summary>
    /// <typeparam name="T">Parameter type</typeparam>
    /// <returns>Generated tool parameter definition</returns>
    public static ToolParameters Generate<T>() where T : class
    {
        var type = typeof(T);
        var parameters = new ToolParameters
        {
            Items = new Dictionary<string, ToolParameter>(),
            Required = new List<string>()
        };

        foreach (var property in type.GetProperties(BindingFlags.Public | BindingFlags.Instance))
        {
            var paramName = ToCamelCase(property.Name);
            var paramItem = CreateParameterItem(property);

            parameters.Items[paramName] = paramItem;

            // Check if it's a required parameter
            if (IsRequired(property))
            {
                parameters.Required.Add(paramName);
            }
        }

        return parameters;
    }

    /// <summary>
    /// Create parameter item from property
    /// </summary>
    private static ToolParameter CreateParameterItem(PropertyInfo property)
    {
        var item = new ToolParameter
        {
            Type = GetJsonType(property.PropertyType),
            Description = property.GetCustomAttribute<DescriptionAttribute>()?.Description ?? string.Empty
        };

        // Handle enum types
        if (property.PropertyType.IsEnum)
        {
            item.Enum = Enum.GetNames(property.PropertyType).Cast<object>().ToList();
        }

        return item;
    }

    /// <summary>
    /// Determine if property is a required parameter
    /// </summary>
    private static bool IsRequired(PropertyInfo property)
    {
        // Check [Required] attribute
        if (property.GetCustomAttribute<DataAnnotations.RequiredAttribute>() != null)
            return true;

        // Check required modifier (C# 11+)
        if (property.GetCustomAttribute<System.Runtime.CompilerServices.RequiredMemberAttribute>() != null)
            return true;

        return false;
    }

    /// <summary>
    /// Convert .NET type to JSON Schema type
    /// </summary>
    private static string GetJsonType(Type type)
    {
        // Handle Nullable types
        var underlyingType = Nullable.GetUnderlyingType(type) ?? type;

        if (underlyingType == typeof(string))
            return "string";

        if (underlyingType == typeof(int) ||
            underlyingType == typeof(long) ||
            underlyingType == typeof(short) ||
            underlyingType == typeof(byte))
            return "integer";

        if (underlyingType == typeof(double) ||
            underlyingType == typeof(float) ||
            underlyingType == typeof(decimal))
            return "number";

        if (underlyingType == typeof(bool))
            return "boolean";

        if (underlyingType.IsArray ||
            typeof(System.Collections.IEnumerable).IsAssignableFrom(underlyingType))
            return "array";

        return "object";
    }

    /// <summary>
    /// Get array element type
    /// </summary>
    private static Type? GetArrayElementType(Type type)
    {
        if (type.IsArray)
            return type.GetElementType();

        if (type.IsGenericType)
        {
            var genericArgs = type.GetGenericArguments();
            if (genericArgs.Length > 0)
                return genericArgs[0];
        }

        return null;
    }

    /// <summary>
    /// Convert PascalCase to camelCase
    /// </summary>
    private static string ToCamelCase(string str)
    {
        if (string.IsNullOrEmpty(str) || char.IsLower(str[0]))
            return str;

        return char.ToLowerInvariant(str[0]) + str.Substring(1);
    }
}